`timescale 1 ns / 10 ps
// Generated from Simulink block 
module decimator_ssr_ip_stub (
  input [1-1:0] s_axis_im_tvalid,
  input [1-1:0] s_axis_re_tvalid,
  input [16-1:0] s_axis_im_tdata_0,
  input [16-1:0] s_axis_im_tdata_1,
  input [16-1:0] s_axis_im_tdata_2,
  input [16-1:0] s_axis_im_tdata_3,
  input [16-1:0] s_axis_im_tdata_4,
  input [16-1:0] s_axis_im_tdata_5,
  input [16-1:0] s_axis_im_tdata_6,
  input [16-1:0] s_axis_im_tdata_7,
  input [16-1:0] s_axis_re_tdata_0,
  input [16-1:0] s_axis_re_tdata_1,
  input [16-1:0] s_axis_re_tdata_2,
  input [16-1:0] s_axis_re_tdata_3,
  input [16-1:0] s_axis_re_tdata_4,
  input [16-1:0] s_axis_re_tdata_5,
  input [16-1:0] s_axis_re_tdata_6,
  input [16-1:0] s_axis_re_tdata_7,
  input clk,
  output [1-1:0] s_axis_tready,
  output [1-1:0] m_axis_tvalid,
  output [32-1:0] m_axis_tdata
);
  Decimator_SSR_0 sysgen_dut (
    .s_axis_im_tvalid(s_axis_im_tvalid),
    .s_axis_re_tvalid(s_axis_re_tvalid),
    .s_axis_im_tdata_0(s_axis_im_tdata_0),
    .s_axis_im_tdata_1(s_axis_im_tdata_1),
    .s_axis_im_tdata_2(s_axis_im_tdata_2),
    .s_axis_im_tdata_3(s_axis_im_tdata_3),
    .s_axis_im_tdata_4(s_axis_im_tdata_4),
    .s_axis_im_tdata_5(s_axis_im_tdata_5),
    .s_axis_im_tdata_6(s_axis_im_tdata_6),
    .s_axis_im_tdata_7(s_axis_im_tdata_7),
    .s_axis_re_tdata_0(s_axis_re_tdata_0),
    .s_axis_re_tdata_1(s_axis_re_tdata_1),
    .s_axis_re_tdata_2(s_axis_re_tdata_2),
    .s_axis_re_tdata_3(s_axis_re_tdata_3),
    .s_axis_re_tdata_4(s_axis_re_tdata_4),
    .s_axis_re_tdata_5(s_axis_re_tdata_5),
    .s_axis_re_tdata_6(s_axis_re_tdata_6),
    .s_axis_re_tdata_7(s_axis_re_tdata_7),
    .clk(clk),
    .s_axis_tready(s_axis_tready),
    .m_axis_tvalid(m_axis_tvalid),
    .m_axis_tdata(m_axis_tdata)
  );
endmodule
