fclk = 64e6;
fs = 64e6;
src = dsp.SampleRateConverter( ...
    'InputSampleRate', fclk*8, ...
    'OutputSampleRate', fs, ...
    'OutputRateTolerance', 0, ...
    'Bandwidth', fs*0.8, ...
    'StopbandAttenuation', 90)